name = "Qt6Wayland_jll"
uuid = "e99dba38-086e-5de3-a5b1-6e4c66e897c3"
version = "6.8.2+2"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
Qt6Declarative_jll = "629bc702-f1f5-5709-abd5-49b8460ea067"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Qt6Base_jll = "c0090381-4147-56d7-9ebc-da0b1113ec56"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Qt6Declarative_jll = "=6.8.2"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
Qt6Base_jll = "=6.8.2"
