[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "3342c99d8652f5c47f03aafef2e6ba0885f60160"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "b109c0098d6e14c2f991fb09f2571fac4161990ff24256aa0de23a406d22b999"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.aarch64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "cc05beebc0ad7df120ce8bc03ef69804e7477261"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "41e64ac379ba8b9fcfa33ff95f7a9095fbd24a4b323b7e56b277b6f73401f559"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.aarch64-linux-musl.tar.gz"
[[Libglvnd]]
arch = "aarch64"
git-tree-sha1 = "9e143f875beb748886161c3bc66b8404abccfa70"
os = "freebsd"

    [[Libglvnd.download]]
    sha256 = "be3284fb678dfd74594a59cc153910e04b73972532e36164c48ada7cfdbe8f40"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.aarch64-unknown-freebsd.tar.gz"
[[Libglvnd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8a3253f08d013cae28e27bc4a9334f564c0e890e"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "0828c45739b934e84fede05962ed46d119fbda4501af0995ac3cbc07ebf1d30b"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.armv6l-linux-gnueabihf.tar.gz"
[[Libglvnd]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "03ceeedd0a1a015daf3e15b37911082af9cae411"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "34b472c2b5a97515d9cac1b9959fa2ab2d77e7de9e7c5e4667a4a75f3b017e02"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.armv6l-linux-musleabihf.tar.gz"
[[Libglvnd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4942484b5e25b0462c2e74a025a91c20e16bde11"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "a5572114005c4f890fd9dbb9800213200535003ba2ac6673a40dc1f03c98d9c3"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.armv7l-linux-gnueabihf.tar.gz"
[[Libglvnd]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "810371eadce9b73339f30f2931b4685dbf962b71"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "ba65f9487d6c7a510551dcdd1c58469182aa2b318585d654d087bfa9c9658c59"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.armv7l-linux-musleabihf.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "ca87fe66126b4ff436da543318e2495a5bd1a441"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "2fde6de61230fda15a855aa0fadc0ab62d4bec72d0902f4934739d4ebaa58228"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.i686-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "i686"
git-tree-sha1 = "485b6ed6fbbf440d066714d8958c11ad8f98642e"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "6ace40070c9d1bdd08d89bc391f5fbd61ec955531e28659bcdbbb5d79302ad42"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.i686-linux-musl.tar.gz"
[[Libglvnd]]
arch = "powerpc64le"
git-tree-sha1 = "c959e5ecd99ac6e118385e5cef38ddf36916b68b"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "38964e4c8a3cad690f4350123e17d3efaa2fd435ff8a0f2297b6c422b8f288bc"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.powerpc64le-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "riscv64"
git-tree-sha1 = "528db4e328abc202d8272544ce70fb27cc753d1a"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "13bbb15fe53256b2262e4ade3dde43b9edeab3e01565080e345c647eb1f309c8"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.riscv64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "52d9b3e9e3507f7b2cf723af43d0e7f095e2edc7"
libc = "glibc"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "6a4b9208a7e532438f86a063dffe0a13b57bfa1e984ee66feceb7e2c40f978fd"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.x86_64-linux-gnu.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "869600460221c5287b1473206d7659b91b5f8d48"
libc = "musl"
os = "linux"

    [[Libglvnd.download]]
    sha256 = "5336f784307c722ef13ad12152b765f5f4999a58165a379278333c44d99c054c"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.x86_64-linux-musl.tar.gz"
[[Libglvnd]]
arch = "x86_64"
git-tree-sha1 = "6372a27a63bd1c2efb8ef03b6455801500883b13"
os = "freebsd"

    [[Libglvnd.download]]
    sha256 = "9d6bccb1dfa9d2bf52d5962f6463289629f834b9c12355dd2d85a1f6af54cd7a"
    url = "https://github.com/JuliaBinaryWrappers/Libglvnd_jll.jl/releases/download/Libglvnd-v1.7.1+1/Libglvnd.v1.7.1.x86_64-unknown-freebsd.tar.gz"
