[[libinput]]
arch = "aarch64"
git-tree-sha1 = "47d2f149c967c1dc2c6338468597c44b0fd41b22"
libc = "glibc"
os = "linux"

    [[libinput.download]]
    sha256 = "773f4b94e1f39ddf55ea915821b62cfdb5dec427ddb9a288f241d7ed5e3eceb4"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.aarch64-linux-gnu.tar.gz"
[[libinput]]
arch = "aarch64"
git-tree-sha1 = "eb5cf584bba89169112d5a0de0d277f4e1cffeb2"
libc = "musl"
os = "linux"

    [[libinput.download]]
    sha256 = "6bf15e993e9a593e2f6fcede8fe4f3ed9c6b30def515bf8d08e330dc26ed8a71"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.aarch64-linux-musl.tar.gz"
[[libinput]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d02b5f3996beaf0562f89045a9252efb8bb76772"
libc = "glibc"
os = "linux"

    [[libinput.download]]
    sha256 = "fdf78ec5c789663c3833154b76924410e4e6211f2836bd3dcfdaeaac1a3afdab"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.armv6l-linux-gnueabihf.tar.gz"
[[libinput]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aa91cbbc076b6d89b4f007a3be1eaef5129bba3d"
libc = "musl"
os = "linux"

    [[libinput.download]]
    sha256 = "2f0c5c9046bb3f111aceca407904a7f5a1f8fd468a039601d75f258f9f91d6cb"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.armv6l-linux-musleabihf.tar.gz"
[[libinput]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0f92b65f5e63adb89f8a6864cdf31828f05daab3"
libc = "glibc"
os = "linux"

    [[libinput.download]]
    sha256 = "a3807ae6d0eb1dd0f5c693b6eae953b20ab85c2fc73436009275b8a8f64d6f5b"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.armv7l-linux-gnueabihf.tar.gz"
[[libinput]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dbd554d2208ef5de9fd6ef69c01ffaff5fa9eb4b"
libc = "musl"
os = "linux"

    [[libinput.download]]
    sha256 = "ffe023579c52a3f698652954d4d5fb98a49fcd59cf1ff3992f650c6a88edd2af"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.armv7l-linux-musleabihf.tar.gz"
[[libinput]]
arch = "i686"
git-tree-sha1 = "68a4c27f412670bc98c7035e6857f03b7434dde4"
libc = "glibc"
os = "linux"

    [[libinput.download]]
    sha256 = "859a70240d50348e071f6d43c1bea9068e330b784efb6349a5b0c4793ba75319"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.i686-linux-gnu.tar.gz"
[[libinput]]
arch = "i686"
git-tree-sha1 = "998ac250b280987dcd052663dbd9fa28bce5635b"
libc = "musl"
os = "linux"

    [[libinput.download]]
    sha256 = "2545bd7e10a75bd1decff6f5efc55db74b08bde9d9d813bb5a43a20cf95e2771"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.i686-linux-musl.tar.gz"
[[libinput]]
arch = "powerpc64le"
git-tree-sha1 = "fb1efd3082f6b0daa61138718f747025e3b5d745"
libc = "glibc"
os = "linux"

    [[libinput.download]]
    sha256 = "784cf749ee78a72e6268b9814a69ff99b850d5e71fe3e0b40b4f19f5beb9ce5d"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.powerpc64le-linux-gnu.tar.gz"
[[libinput]]
arch = "riscv64"
git-tree-sha1 = "ba63f4cc03cbc477a47ae39a7afd433b86d5694d"
libc = "glibc"
os = "linux"

    [[libinput.download]]
    sha256 = "90128667cd07db7f51e5e30653aa005b627962f36325657bb62f11362332ff36"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.riscv64-linux-gnu.tar.gz"
[[libinput]]
arch = "x86_64"
git-tree-sha1 = "641f192fccf3897c9bb53cb8edc1e0cbd316488f"
libc = "glibc"
os = "linux"

    [[libinput.download]]
    sha256 = "94bea32f093cf340058f3b202268dc81430e692fc2bb005a39a9641eea47568a"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.x86_64-linux-gnu.tar.gz"
[[libinput]]
arch = "x86_64"
git-tree-sha1 = "c54bf32342468c61a47149ffd45e1071a98fc4b1"
libc = "musl"
os = "linux"

    [[libinput.download]]
    sha256 = "7ac5aa0e77f05ce489a5ce5a4606ad4401104c68a6b11d28ecd27bda6ef1308f"
    url = "https://github.com/JuliaBinaryWrappers/libinput_jll.jl/releases/download/libinput-v1.28.1+0/libinput.v1.28.1.x86_64-linux-musl.tar.gz"
