name = "libinput_jll"
uuid = "36db933b-70db-51c0-b978-0f229ee0e533"
version = "1.28.1+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
eudev_jll = "35ca27e7-8b34-5b7f-bca9-bdc33f59eb06"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
libevdev_jll = "2db6ffa8-e38f-5e21-84af-90c45d0032cc"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
mtdev_jll = "009596ad-96f7-51b1-9f1b-5ce2d5e8a71e"

[compat]
JLLWrappers = "1.7.0"
julia = "1.6"
Libdl = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
