[[Glib]]
arch = "aarch64"
git-tree-sha1 = "0a2974ab6286ff434737b70b715a26ec7a236548"
os = "macos"

    [[Glib.download]]
    sha256 = "654a4d6474efaa6ced269561f0d40adab7a2618c9b188e2f27c4e64812d5c03c"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.aarch64-apple-darwin.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "39620792f8a8587f0f5f571332c79201aa851977"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "275ee872399cd6b4339354b77561ecf257e41fbf0703bea888a4cf00720c2de3"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.aarch64-linux-gnu.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "f81a0b3c1f22a974497e6fbaeb6e8af45827cd12"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "a4c27f60d55850c9c7ec46ba391cb8a05bfa65739e29dfa0a09e412b7818f0a6"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.aarch64-linux-musl.tar.gz"
[[Glib]]
arch = "aarch64"
git-tree-sha1 = "06fa581e8861b196caf2f7ab26aa1db41c30e522"
os = "freebsd"

    [[Glib.download]]
    sha256 = "b7bfdb9fb47d5d9090f5578b3cf1572713c89d2cc7349e924e5c812a529ca80d"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.aarch64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "db948bffbf8c47ace66dd24b466ad73e2c21f2b9"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "ea8191511f378fa2e8c88ec4ccd5f9c39ebdb03fad661c45178658899f7e8f5a"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.armv6l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "84b116e6cf1effe84161410a8d030e7a00f99caa"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "b1bbadae9293b9490ec86f4e69822b82ceadbadb5c5e9f5830e2f65546c84824"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.armv6l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3bc88f5f648ea81e5dafc63e954e37cb1ead62ff"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "32fcadab2307ccd06837567498fd8dc0a7264f5307ae6f9f3263e8875a98aa72"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.armv7l-linux-gnueabihf.tar.gz"
[[Glib]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9042e9c5f0ad763f3b26537fab364d9a99da45ea"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "62cefaa64c1e4d09b66b8254cf4106656f2c5790b117c010bced1cbefecd6d1c"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.armv7l-linux-musleabihf.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "979d9864d956674043a5ea5c56945b177ad2d6df"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "c0cc5a191dfaab7d65c0032abf0469202fba828a7ede2b6928ed979057302bf0"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.i686-linux-gnu.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "360ee870f50332e0a4111ce976405bb59834167b"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "93a5a98a1db886f9b0ea4048c109a6c7f2d7f8560c0e4f327b7e83899cdf71da"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.i686-linux-musl.tar.gz"
[[Glib]]
arch = "i686"
git-tree-sha1 = "4620d6002435bbd420d5e44aaf324b97a35e58f0"
os = "windows"

    [[Glib.download]]
    sha256 = "18cb274232f16dc46bf98a6000c17f88f2a419ca95c8ab1eb6823fd94d8efbaf"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.i686-w64-mingw32.tar.gz"
[[Glib]]
arch = "powerpc64le"
git-tree-sha1 = "625c6f3b90980c46ec3b28089918be263bd52eb5"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "d60bc6198e46dadf49f13333f788c06d8c3550a322e0a15bc09a7cfc063d5277"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.powerpc64le-linux-gnu.tar.gz"
[[Glib]]
arch = "riscv64"
git-tree-sha1 = "fb29f4621352c5ac60602d7fb58779c669fdc7de"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "b1f6ae730b45c29bc946fb4180d4946075c486455f8dcb301cd81a7262de156b"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.riscv64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "e858455bc0b205252093b3fe30790fa630740f64"
os = "macos"

    [[Glib.download]]
    sha256 = "9e2bbfc9ffd21051c6a8c4fe538736853a52284a67ddb70eda39b44d0e260eeb"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.x86_64-apple-darwin.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "3f1128f05e58ae4264bcad52869c9a9f766373d1"
libc = "glibc"
os = "linux"

    [[Glib.download]]
    sha256 = "19a46124f64022fc7fd666a4d2c78b7edfa000474ec414db22b1267df0675acb"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.x86_64-linux-gnu.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "2cbe6e1dfea35417f50eb01b809d756551966357"
libc = "musl"
os = "linux"

    [[Glib.download]]
    sha256 = "92de32e50a26f97b919197b350d4ddc0d1ae6efbdd268bcd66dee22f8fa53ec7"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.x86_64-linux-musl.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "b325aadbd63b0939774939fe5d26945391546d5b"
os = "freebsd"

    [[Glib.download]]
    sha256 = "eed6b894a5e2fce7f4c48f90c68b74ad0c189480b5b2d801797e1dd16451480d"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.x86_64-unknown-freebsd.tar.gz"
[[Glib]]
arch = "x86_64"
git-tree-sha1 = "2e28442353abe19ec2558fdfae0031715f7dc1b6"
os = "windows"

    [[Glib.download]]
    sha256 = "aedf399dd7c786a726a02eea57d3082f46a7427081aae0c98ab069484442c112"
    url = "https://github.com/JuliaBinaryWrappers/Glib_jll.jl/releases/download/Glib-v2.86.2+0/Glib.v2.86.2.x86_64-w64-mingw32.tar.gz"
