[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "226fe34989557ac27bbd60ea8ab90bb7a4c58dcf"
os = "macos"

    [[GLFW.download]]
    sha256 = "0965efc7e3d51b8ff93d5aa8add31c5d4c74cf424aa64d83b3e5288384cd93c1"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.aarch64-apple-darwin.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "5790954dded7580fbe98deb6ad58f2a3a775d5b8"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "09fd165d90405b77d84876d88592cdfe3d84fd723bab33fc9a82d53f5d37149e"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.aarch64-linux-gnu.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "a961edbff5a2f11b9bd762ea6c7ae25cfa0eeabd"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "68cec29b5b9fe5e703c6b379e4d5a521ef54ae1bb0ccf10372deb59218aca718"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.aarch64-linux-musl.tar.gz"
[[GLFW]]
arch = "aarch64"
git-tree-sha1 = "d81b1ef19323cab3ad9e365f155efc90275a6a48"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "c5b78a7e7d5a5b3a2f93829e7968f64d4e9de528122efd8d77ff75927d595f82"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.aarch64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "72ab1d977d45293e52acddedff8f790741b353bc"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "4095cef462d5604573ffe7b9d14978a7bd6c9b3b6faca278929503ef66c11dcb"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.armv7l-linux-gnueabihf.tar.gz"
[[GLFW]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1678598d5650bb3a86a452d4d5b0849589037d6e"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "f9b9e311e02a8cab8d2b1d207f69225af6429fea7f40f9cec4ec4a3cf31328b5"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.armv7l-linux-musleabihf.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "294e10b1845ea1637381ad0408eae9e7e60a6cad"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "706637816e81c1e39ba2a07df3515e54e3a499c309dbfb696251a4d447a2989e"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.i686-linux-gnu.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "f13b5ba5be85628ec353fe061a06740ac8e883ea"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "13805a960468dbecfb79ec1b8a557edfb554fbcfe46110795cad08eee7da9098"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.i686-linux-musl.tar.gz"
[[GLFW]]
arch = "i686"
git-tree-sha1 = "5e9a2909f8de5c57c18f81a41a86adc10026794c"
os = "windows"

    [[GLFW.download]]
    sha256 = "08ff250f6c00c8c48db2b3d064f524575a943728752a43295cd8c966a9dd179a"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.i686-w64-mingw32.tar.gz"
[[GLFW]]
arch = "powerpc64le"
git-tree-sha1 = "0f44c35efb6ed00311b1088e1f0309632537d1cc"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "0162c6318e75a34e6c36cd807121e2583103a5c8bfc1079a1eb93f5d460b40db"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.powerpc64le-linux-gnu.tar.gz"
[[GLFW]]
arch = "riscv64"
git-tree-sha1 = "94d745e9a99bfc15dac9c372405020ef767eedea"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "9d39fdf96b6c57d866ef6bc9854877b5ebbf03a69e64ee2c2053343836a6be51"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.riscv64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "34c97139039152f08e86e7e9f1110679c0274d39"
os = "macos"

    [[GLFW.download]]
    sha256 = "5e70ff43ec3c097848cdb5a2e838dd970895b39367545fb4e96d89998a3092f7"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.x86_64-apple-darwin.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "a98a61fe400fc88f9d0364b17396d063c1bcf20f"
libc = "glibc"
os = "linux"

    [[GLFW.download]]
    sha256 = "b413f316d5f3208a7d012ea762a4b4abd5bedb76b6b047fc77176b5c224c01ee"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.x86_64-linux-gnu.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "e857e49ba80ab16516038fe2c8588739e77a0540"
libc = "musl"
os = "linux"

    [[GLFW.download]]
    sha256 = "989340765ba5a980b30bb175c71967ca31b068bc3027ceef3a67df44538bf1a2"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.x86_64-linux-musl.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "9959f33498c83ddc10d25f38b60ffb29cd1a630f"
os = "freebsd"

    [[GLFW.download]]
    sha256 = "b462ef3cdaacc7723e2011ee5e3798153a2637ae8c5b15b1c82fc0245d62ff9d"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.x86_64-unknown-freebsd.tar.gz"
[[GLFW]]
arch = "x86_64"
git-tree-sha1 = "d7db35a275365492ebada4fd9c096717fa8c689e"
os = "windows"

    [[GLFW.download]]
    sha256 = "ffe1a79f02ed7c698a3c6e7ae4c6335e7a5256f9c65f1941a139a1417915f94f"
    url = "https://github.com/JuliaBinaryWrappers/GLFW_jll.jl/releases/download/GLFW-v3.4.1+0/GLFW.v3.4.1.x86_64-w64-mingw32.tar.gz"
