[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "7fefc9739781f053e15aeb2e61c2ba767c275222"
os = "macos"

    [[HarfBuzz.download]]
    sha256 = "003dad61f9391fc57b0ff06e0a8bfd4a286484cb9685ba13b5e2ccfa221a1339"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.aarch64-apple-darwin.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "335a5d1ae8be9bff21c4d1f7cb7af69890ef7b88"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "d36e69b8e73d7469953e0804e3c15e13fae4bfd7ed698c94d9d12f9ccdacd411"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.aarch64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "e0e1d821c944400dd69a8318e2698235a3c3fb6f"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "ce56d42368ba478979b1e67d4b542f6323465813bf59351fa010fec0e66f495b"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.aarch64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "aarch64"
git-tree-sha1 = "2f5565faff8000b2945e57aeaf9579c109c2453f"
os = "freebsd"

    [[HarfBuzz.download]]
    sha256 = "8f319f547fe8dd8a90750dfa01d3324201a45570a271ac1eb094e63c0e665694"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.aarch64-unknown-freebsd.tar.gz"
[[HarfBuzz]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7119bac5d1a9754a5152080e0494656e1b2c63d5"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "e58a4ff783b0d3ec4d3dab17b06f4a1e6b6218befa68b62bab50a9b27f3fd59e"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.armv6l-linux-gnueabihf.tar.gz"
[[HarfBuzz]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ef8f4ea88e8568422874f7215baf9452bdf78dc1"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "7e0128d37d8e9259e86626dd44989fca639130971d9c526adfa2bd939229ad2f"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.armv6l-linux-musleabihf.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "52392d89cc660729134880c29ad3ff7fe19b6aa7"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "479ce88671ee2149229929ac38ac1b756f598e46e9a7abbb4d1509d1d2b7673e"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.armv7l-linux-gnueabihf.tar.gz"
[[HarfBuzz]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8c21b191716d246bf70418d64301952857019bae"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "85d91d047acc52cab97d903b952e26676ea5ea2575bdb4c8e60d912d24bfdbcb"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.armv7l-linux-musleabihf.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "e1d8b52aa3f66079b242a3a5bfa2cfafc88d07e7"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "7f3e273fb277f037f6fd7bd8d3e4451615a932fa13046b0715a53af301bd9eac"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.i686-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "99127f3e69d45492c8641cdb469f299f6c1646ef"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "96a14ea974ac16fb95010a3757be08737a3dd83b7b00d48d2e374409147a286e"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.i686-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "i686"
git-tree-sha1 = "ac8b5512ddb27f73addded33bb35db8239175c41"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "87adbfe55c439cc85df32dc21aae9835f6e948925f34f10f47154e3debe2eb9a"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.i686-w64-mingw32.tar.gz"
[[HarfBuzz]]
arch = "powerpc64le"
git-tree-sha1 = "27030a60410fb0ad1d4b5d0686a3629060424848"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "4ef002b8093e4cfb81e048db89fb0c2c9c73f868e75bac7668e2777c6d87f668"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.powerpc64le-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "riscv64"
git-tree-sha1 = "4e0891599860a9b789280084a009c5a0eca29044"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "d88b1da9fa10cd44e402be3053fb0be47ac49df66bf6be394a708559d1527885"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.riscv64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "f1dc36ad336569c0a7be13b9093b155c25aac954"
os = "macos"

    [[HarfBuzz.download]]
    sha256 = "233d2df3921e0847f2a77b98ac238ab09b90c483ee20b1790658af8f61ce55d5"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.x86_64-apple-darwin.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "5c030ff72c13f84fbbc8f93a146e34c6219a0261"
libc = "glibc"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "e81cdc81df2d2eae3a3e8be262c200a353f72c583fda6571bf511766a99af2cd"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.x86_64-linux-gnu.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "534d40cdab44d209e4c9b0d395df695a8a7ee917"
libc = "musl"
os = "linux"

    [[HarfBuzz.download]]
    sha256 = "a674a90f364c68ae79205235a4d1fb74df2cd54e42c795dea2e9e1c9a70ef2b4"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.x86_64-linux-musl.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "2b5a5f04b143cf307880a626c97ff024f6ef29af"
os = "freebsd"

    [[HarfBuzz.download]]
    sha256 = "f5fae36a1ea66c88da95c31fb754e31ae9f14b3e3ec42963b2f127af80f481c6"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.x86_64-unknown-freebsd.tar.gz"
[[HarfBuzz]]
arch = "x86_64"
git-tree-sha1 = "8d9f87bf9e08a0e0db47c0ab531ee29fff143eee"
os = "windows"

    [[HarfBuzz.download]]
    sha256 = "2bda67ae2392edc541b7d6bb130dd2b000de9a2384c8c80e6fb0d36e3d882934"
    url = "https://github.com/JuliaBinaryWrappers/HarfBuzz_jll.jl/releases/download/HarfBuzz-v8.5.1+0/HarfBuzz.v8.5.1.x86_64-w64-mingw32.tar.gz"
