[[Pango]]
arch = "aarch64"
git-tree-sha1 = "5cdec74e3c8a3f097c5a0397169d304bb6b59e48"
os = "macos"

    [[Pango.download]]
    sha256 = "9fd6249de8d95431eb7be0d05418b82e59478c0dfcb69680f3a998f1cc9b84d2"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.aarch64-apple-darwin.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "e430fa150e42c80662b5f0b19a554a73ce15d70a"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "446fb37ccea0ef1bfd374d25edb16887c13acdfab149fe629143f8e45803ee8d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.aarch64-linux-gnu.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "6a6424422ea98bc5e04645866c9de96ecfcfe4a5"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "e5e3cf61591a12d96a5f45118e6235a35e14cb9ede8eba80ce451798f9eb878f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.aarch64-linux-musl.tar.gz"
[[Pango]]
arch = "aarch64"
git-tree-sha1 = "7f19b622957e1ca12089e41ac5bafa78b46a1044"
os = "freebsd"

    [[Pango.download]]
    sha256 = "a87befa7e1cb1ccfbdef756f892681f6bb35df88568907764914b29e29445d3f"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.aarch64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d587859efb344de998b4685a6b45a3fce51d2534"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "089fef2aa047ff0312471ebe6e15eac7cceb4715bdc4b369221409e0d61abaab"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.armv6l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cc53cb2f0a4e6f209de90aa8a5e7d629616d2707"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "20f6d443aa21e6fda5b49f1bbb7ae27442e174ca3a2003afa39e7db36994e84e"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.armv6l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb0484c05d966d571fda55da8b50c1e532949970"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "38890c2879dfaea15009976ee97cd2a848bfb5d305f7d11bd781119ff5dd31e9"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.armv7l-linux-gnueabihf.tar.gz"
[[Pango]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0c4ece1eb475aedd0c27c1203668ebf09159f5c"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "5d82c7d54672e03f3f5570a4e69f99e88881fa4b71ad69b68e78415a8d70b8aa"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.armv7l-linux-musleabihf.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "e88a6ccabacb6884691ffcd1fbeeae7e351ffa16"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "472e68d7f06d3dcb85b1bfd491ebc0e3416a09ec0ea20ce9727e38ee04e4f66b"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.i686-linux-gnu.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "c512d23a7374874117e962ed6002f0eb058f2250"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "d8754e1b86841371a2eda63ff843388ad2343e5991ecaa90f4779c7a5c8e0864"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.i686-linux-musl.tar.gz"
[[Pango]]
arch = "i686"
git-tree-sha1 = "b6297c69723ede2f2abf92cd816e9935cb0d44bf"
os = "windows"

    [[Pango.download]]
    sha256 = "a99dd06872a1c63d2b0443e2849db6e97e40db893f20ea24a4f66c2e6b0602d4"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.i686-w64-mingw32.tar.gz"
[[Pango]]
arch = "powerpc64le"
git-tree-sha1 = "77bf60d22e897a74b0ccce303ce2e452839db975"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "770a1459fea4c1fc842bc33411923b49d0d7539655ed773687d9507ce036dcc0"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.powerpc64le-linux-gnu.tar.gz"
[[Pango]]
arch = "riscv64"
git-tree-sha1 = "84c9b04634f137021420edb9e88445e1540cd5ff"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "d1f1b5d27e1bade47f2da2f9674297b003500df800a3492fc87a77bf0d064df0"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.riscv64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "71c827b6927305be52197bccade0f2123df11f74"
os = "macos"

    [[Pango.download]]
    sha256 = "7119be7416820d9e73900623b109edb69617d3e5f9acb9ec9ce4f77e0b75afa6"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.x86_64-apple-darwin.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "b2e490a224990d92e99cc4463b8df48c8c454971"
libc = "glibc"
os = "linux"

    [[Pango.download]]
    sha256 = "34c582c3ad6da25aa366df88c2f86915dc61893213d15341b61f268968f1911a"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.x86_64-linux-gnu.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "4fc502053e7881e68bde2c54a2d0c70a46dc1fb8"
libc = "musl"
os = "linux"

    [[Pango.download]]
    sha256 = "d5ae77d2dc236382be3314fa59b40d3c163e16a4f346f59b7d1da2ed987311f9"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.x86_64-linux-musl.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "b81589685ee373b355ffbd571a8b5e1066e12f51"
os = "freebsd"

    [[Pango.download]]
    sha256 = "d2d50f21c724a2ceb6b7e38e762533a7811fcda88500025191c76805aec4e77d"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.x86_64-unknown-freebsd.tar.gz"
[[Pango]]
arch = "x86_64"
git-tree-sha1 = "7ea1a3ee7941632335312cb50c7ddd3fa5ba4e94"
os = "windows"

    [[Pango.download]]
    sha256 = "f7784e7198170124e518430549e103d5e853a06a233d5d7b0f8226f870aaef56"
    url = "https://github.com/JuliaBinaryWrappers/Pango_jll.jl/releases/download/Pango-v1.57.0+0/Pango.v1.57.0.x86_64-w64-mingw32.tar.gz"
