[[x265]]
arch = "aarch64"
git-tree-sha1 = "c70ffd15b6adfc269b041a77ed26af364f9969c4"
os = "macos"

    [[x265.download]]
    sha256 = "46da96c4c31a970f469e12886c0734de0c88f42afdf215f24f2254f09b451b1c"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.aarch64-apple-darwin.tar.gz"
[[x265]]
arch = "aarch64"
git-tree-sha1 = "4c62e405e85fd9c296a8cdde03b19c5f88f188e3"
libc = "glibc"
os = "linux"

    [[x265.download]]
    sha256 = "7c1dc66a00c1d677c26cd77bc89167918f5f2cf70378aa3c7619fc6d5b776716"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.aarch64-linux-gnu.tar.gz"
[[x265]]
arch = "aarch64"
git-tree-sha1 = "3b254b8e09708c10c1711438b6204343ed732717"
libc = "musl"
os = "linux"

    [[x265.download]]
    sha256 = "e51fd5b938b905f3db53dc09871fc3cab58857eda962c3e8e1eb97cede8acc98"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.aarch64-linux-musl.tar.gz"
[[x265]]
arch = "aarch64"
git-tree-sha1 = "8ccc9d6195728947bd9882ed14375b8404c7ecc6"
os = "freebsd"

    [[x265.download]]
    sha256 = "05307931c275f5b39a942d8b8b0fee35b0b45191d2db2ef8d21804407bfb99fe"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.aarch64-unknown-freebsd.tar.gz"
[[x265]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "889b53089cf36a8d686f17f3a67fae54f4cb554c"
libc = "glibc"
os = "linux"

    [[x265.download]]
    sha256 = "82b4875349167e46225de585464054da6485a9e040776cae1bcd60260469fc33"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.armv6l-linux-gnueabihf.tar.gz"
[[x265]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ea6797c506ae66dadab85408c2d8a520a8c4e157"
libc = "musl"
os = "linux"

    [[x265.download]]
    sha256 = "37223753265fec1b4ff74aaa1fa728bf482f608bf64b539a9e7d4737b86d82e9"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.armv6l-linux-musleabihf.tar.gz"
[[x265]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c0c7d0faa9d299ef96083c33db8b24a65c3019de"
libc = "glibc"
os = "linux"

    [[x265.download]]
    sha256 = "8d050419f11ccdc735bc6521aadb86a2b8d4c145a7a3d1fe014a0552ab3de4e1"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.armv7l-linux-gnueabihf.tar.gz"
[[x265]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "efc5b0da15339745c2cabfdf0bd23477d5f5f524"
libc = "musl"
os = "linux"

    [[x265.download]]
    sha256 = "3ca1164ff210f13f1528f29d9a9651b0de91755d23ec245a1a1890745b4bd6a0"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.armv7l-linux-musleabihf.tar.gz"
[[x265]]
arch = "i686"
git-tree-sha1 = "ed0381c877158be769fda23aa11e09c96a4c5b91"
libc = "glibc"
os = "linux"

    [[x265.download]]
    sha256 = "b92956d77bcc27f074eb6e6b51018dfde5cdc1eae51d24132175f2b9b8424a0d"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.i686-linux-gnu.tar.gz"
[[x265]]
arch = "i686"
git-tree-sha1 = "6984a1ac3d51c28cbd3c89bea3bab748e2a7a149"
libc = "musl"
os = "linux"

    [[x265.download]]
    sha256 = "51181abe792845f8172e9df4752f532f94ae5c616bd4bb70fbc3f5050de78fa8"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.i686-linux-musl.tar.gz"
[[x265]]
arch = "i686"
git-tree-sha1 = "032ea8deb066d74046ab6bfede6d4a65e4800690"
os = "windows"

    [[x265.download]]
    sha256 = "baed1af52fc2bba1fdb2f42b6539ac873f4331f01584aeda7d3bfc22e6403b8b"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.i686-w64-mingw32.tar.gz"
[[x265]]
arch = "powerpc64le"
git-tree-sha1 = "8a5c6ea7dc8050030481d4effcb6ab8a038b5365"
libc = "glibc"
os = "linux"

    [[x265.download]]
    sha256 = "3780dfc7cdfb575b3218acb9d8af6d8663098fdeb70a48f4b94aa38ed45a8cf9"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.powerpc64le-linux-gnu.tar.gz"
[[x265]]
arch = "riscv64"
git-tree-sha1 = "d0dac10e66c244b259dd22d893e980348d1ca543"
libc = "glibc"
os = "linux"

    [[x265.download]]
    sha256 = "554ce45e5625bdd9d87633eb76d107751f7d78929bef7645cc9d9b7fa2e1554e"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.riscv64-linux-gnu.tar.gz"
[[x265]]
arch = "x86_64"
git-tree-sha1 = "1adf0a7e4c842ab9addef6fd022d726db58cb7a2"
os = "macos"

    [[x265.download]]
    sha256 = "ceadb666a4483ad8ad2cb4dcf3122dda3130174ffa48e17f6cf85053a1d20850"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.x86_64-apple-darwin.tar.gz"
[[x265]]
arch = "x86_64"
git-tree-sha1 = "c9533bea1f28a1adea8cb096009f360534f7ba90"
libc = "glibc"
os = "linux"

    [[x265.download]]
    sha256 = "6623f97bea74f1cb8e5b2dfba5bf5a71ed36f4a5906f49434dfb9b3521896d31"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.x86_64-linux-gnu.tar.gz"
[[x265]]
arch = "x86_64"
git-tree-sha1 = "4986eb4acaf3a3eb6f8486badc529e3944b5a4ae"
libc = "musl"
os = "linux"

    [[x265.download]]
    sha256 = "e4e82fafe920003dace8e7780c98cca4ba3375c9489ccbed8cd604782d5bb420"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.x86_64-linux-musl.tar.gz"
[[x265]]
arch = "x86_64"
git-tree-sha1 = "8e9085602c7d6a37747bd3b2ea14cd52d7d8c140"
os = "freebsd"

    [[x265.download]]
    sha256 = "8cef2ede435c72aaf048ef1a4c12c874914db711c5fbf67398797c12d6934ab7"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.x86_64-unknown-freebsd.tar.gz"
[[x265]]
arch = "x86_64"
git-tree-sha1 = "ba2dc75245508e0cf0c860081b2f2fd10bdf4357"
os = "windows"

    [[x265.download]]
    sha256 = "5a1227f9a4b0fbc1235387396a547d3dfee6c078a69f634d63cb814c93d3a1ac"
    url = "https://github.com/JuliaBinaryWrappers/x265_jll.jl/releases/download/x265-v4.1.0+0/x265.v4.1.0.x86_64-w64-mingw32.tar.gz"
