[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "efc0548ac54d987de4c2dbaea3503797a4b4c676"
lazy = true
os = "macos"

    [[oneTBB.download]]
    sha256 = "a85f7e8cb657b6a65c13e912056ceb19ccf0674810f2ce9da0ad314780cf9a3c"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.aarch64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98ce378fdf3c79e062b74cfd02e31fc2da3fc097"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ea8b8ac63df769cb13adc07da2393ee1b0dd7f3181a4711a56ba8acb1469b493"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b124ac103fd5b8a9c36845a98a3b4e7bb2c299d0"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "30eb404e5e4d4617b4177a4098efd48dd8739f0b5faed34688b619117641a0ee"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e49d24d838f9b8c24ea61358a196dd9a37f0a6e4"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "d1e6af7ef280da38c8e1c79dda46e300b4254018dd8623f794b40fbfed00d13d"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "346883a1279da5b73eacb4ec207e56d1ded50e8c"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "c4d8b786723936626104a74a4d59e1223bc3f28084e118e599e2bebf611d36b5"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "aarch64"
git-tree-sha1 = "6a5e26c57a27bdd454109b3414dcf7c3e67efcfb"
lazy = true
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "7a02d9d977d3de7b3df3a5edde76d5a163ec5ba5ce3aaab6cb64a3fe3a86e6a9"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.aarch64-unknown-freebsd.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "47071e869b95020b9524468d0cc1797bb477935f"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "76202bd5f80d125b6a18a5e4fa73709210400a53c88ab8e300093a8eca6dece2"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4e1a04b0a382e3a902d3b8db37adb9807f9832a1"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "30745ab06d65c5bea603391fe4db7b41d1cabfbe923c68334d9c7ad1c5dfdcee"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c9ed5305c85ccb3763c552523bab8bfb591d9053"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "882f982ccdbc665c3e63b9566a4b9547723f5e93ef5331da3188dcfb8bf7ac6c"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70dc90a50f866f4beea6f303e9a27fb7639ecf3b"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "246f58f10579ea8472da7bce5e2f82aa3d21bde80a41229d2f0f98bece2e7748"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "914a6452b1d1451162cfd66476d866d5410feb7c"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "b77883c1bb91d79dbef506e9651e0ffd0cbcc0cb0dcec6bf0f77ee33a3de651a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2c85f9a9d6a50abc375221b9923e80168876de1e"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "b49b789a70f4ab22916f76bb9fb452c700a027ba0a480bb11d661c2b9fe50afb"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6daca90bb501d955ba30d7741d541c07f531bd08"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "fde6aab99ed3cf7dc222af73f91c147fe154f9ae0a96ace5e013df05daea9eca"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[oneTBB]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f214c325c8cde1df4aea19b35a56b561b74d1b9a"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "d4c2c6bf1face8b2417528ace2ab176b1bbf5eaf92ed768dcf98a422aef83769"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "92392fa559f45f08c4836d6a858500518c68e5fc"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "7ddd36748204e178f0f1684fd7b3c404e1b0c59cd12583398db4782236e0eaae"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.i686-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0684ec574c570ad4b368cecdab9b31f1fbba99d4"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "f503a9345853ba0958f14053e9ab6ccb63c8b6e306bf6bba763114e6ab625156"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.i686-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6bda27527120366c75ccbbfb983066202616583f"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "a1389898f800b8e7105d0e7650f6a4cc4c6bd4b5f9a8b8b3f337f2f60d2cdb30"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.i686-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "caf3e80b1a2f34196d36952b81f22027d20a3d80"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "595d5b10b8a638c7ea10f8f5099eb970fb0f6157ef1bf4ec7371495fc5b88fc5"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.i686-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f1a2aa2fbdd346f8c15bb979b8266430cdbc7fde"
lazy = true
os = "windows"

    [[oneTBB.download]]
    sha256 = "64cb1fe07bcd9e65c0a9ce7406d94157fd922bd07abb98c69badd72ddcbc7f6a"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[oneTBB]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d98236156c74e7ad269e5fae676b7f829842b40a"
lazy = true
os = "windows"

    [[oneTBB.download]]
    sha256 = "8ee191949c2974541b8a1630d1ebee6e4d94ff83b2bdd54f27d4518c8d6f1fff"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b765fbcf6340352221b5b840256ee0b7039626ff"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "ac78f774c3a61750680177c1c0c312d2b1f566021e12555dd1dc60c9c82612e3"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a67bbad182a74605a35ed72a61868397caa2e81d"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "b31177826e2f54222a9d2e38c26d0845009fa283a5b11dbcc7296bc4543aa73f"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "riscv64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "127eb70f13a6fd218918778fae1e1e6ac3ba41c8"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "5dec3e8ce4f31fbee3fecc799f78dddff90fe247a70869082b0a8da91780c9a9"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.riscv64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "127eb70f13a6fd218918778fae1e1e6ac3ba41c8"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "5dec3e8ce4f31fbee3fecc799f78dddff90fe247a70869082b0a8da91780c9a9"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.riscv64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "e0af13d4fb7615a4ea97e9922c8ac5a902924608"
lazy = true
os = "macos"

    [[oneTBB.download]]
    sha256 = "8b1561a6137f4fcd77be5b11c75b089ba9abeaf4f873512d7c5ec91e24057864"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.x86_64-apple-darwin.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ae518083b9220f92d4ea6a3579ac6924b60b5d9e"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "5f0d8a3db603507f45f9891af8d3322bf2c32a7e3b5c3bef228a16f396d66ede"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9723cba3628566f8da50ea2f286daaf70c23a7a2"
lazy = true
libc = "glibc"
os = "linux"

    [[oneTBB.download]]
    sha256 = "c65af77e70170d9843527a222ed09873822f894dee71b50c1468d5e99bfb7beb"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91c901ec414a23b7b3e2c971e938338a5055df46"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "201d2f253bc7fe0eb35be3c99605d6e97f912e20db1005b8518c32f8116345cb"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2182990fa3fdbddf098ee73d2b760deac5a88b2f"
lazy = true
libc = "musl"
os = "linux"

    [[oneTBB.download]]
    sha256 = "613e978ebb004a7bd9fcf3da01b540189bfc53833e5b46e8ed054c3fbcabb77d"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[oneTBB]]
arch = "x86_64"
git-tree-sha1 = "faec5694f61a6b1c17f9318b37fc51e4f64ab96b"
lazy = true
os = "freebsd"

    [[oneTBB.download]]
    sha256 = "f37ef34844995d5d21c3fb900816b1967f3a9fe15a6ad69c0872d411fd1f0352"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.x86_64-unknown-freebsd.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "671a5dd371b492520e8be8531f6f473ad9884d0f"
lazy = true
os = "windows"

    [[oneTBB.download]]
    sha256 = "3d49f42ea7e6852d09321f2764a577b6b22bb530f9de354e5b5c12b9bcc58cf7"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[oneTBB]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0d54e3cabd3ab0ced7df4e4f4b49a46965fa9579"
lazy = true
os = "windows"

    [[oneTBB.download]]
    sha256 = "ba7ba42afbf62e40186fd0c684b30910f2f9289527e56b73a41537b51e2d20f4"
    url = "https://github.com/JuliaBinaryWrappers/oneTBB_jll.jl/releases/download/oneTBB-v2022.0.0+1/oneTBB.v2022.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
