[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3de88ca38311ebd7a846b8bdec7f5edc01e8b06b"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "fed2a9090f023779f4f18d91bca2bcb89319a6e8628febbb307a7f7f04db1de7"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe0cb19fbc9b545a1dad52a8495021f5c703d792"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "2ebc950ad2ae78a6511f31260ff18989868d7f8460059933be59eff6eac48b43"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.aarch64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "f0b6c609330a44306f1a2412b07b4695f2075f6b"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "a69eba6b5c25057fa8efc0e3df557db7128d769823e8d66b96567716d8184838"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "f9c0e05c59a452d275b23a3147e58e673bad020a"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "macos"

    [[Reactant.download]]
    sha256 = "d8dbeab2c19386079e1354d489aa9217d2429b1c233ca10356b5dd3a8e63b558"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eb37440426e0dbe59f72c6b4ca460f5b54408cb"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "opt"
os = "windows"

    [[Reactant.download]]
    sha256 = "673bd6f6be612948a1d2c2e185b579f5f2d697df09a6e175caa5b6dcc88a70b9"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.x86_64-w64-mingw32-cxx11-gpu_version+none-gpu+none-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5f3b9fa99bdbc4453875874b53b6499de8507d51"
gpu = "none"
gpu_version = "none"
lazy = true
libc = "glibc"
mode = "dbg"
os = "linux"

    [[Reactant.download]]
    sha256 = "b30bc26cb569a090e684d42a7dbaaa49faa29aab8ccb51860f3414760cc6fbe1"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.x86_64-linux-gnu-cxx11-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
git-tree-sha1 = "55c71b7836cec4574c0f9193f83c08be08be735a"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "1a174f00cd66e7cb715ff74e3ca6e6013b39332fd783210508a89bb32f207ac0"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.x86_64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "aarch64"
git-tree-sha1 = "b44d7e011bff835bc24af773aeff251a308660ba"
gpu = "none"
gpu_version = "none"
lazy = true
mode = "dbg"
os = "macos"

    [[Reactant.download]]
    sha256 = "2d1a2a0b5335ee637220a7db6073d95eb76187ee7804bd717c64480d9368a9da"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.aarch64-apple-darwin-gpu_version+none-gpu+none-mode+dbg.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2fb8a466f6db4134b05bb496bdb8e02c53aa3c51"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "6ee928cd46e5017a51aaec51bca89a37f09a1698d52f71a003976c27b4edfc9a"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.x86_64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3be5c1e2c724e404c4b8240f7fdb72aa7ce052ae"
gpu = "cuda"
gpu_version = "12.9"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "0e25fd1b4e4777f5dd42f9be64392335e4bdcea87f0a9a08a4d1d6859082d263"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.aarch64-linux-gnu-cxx11-gpu_version+12.9-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfd689b63c50f55db89bdb1340483cc7c32ac1b5"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "56ea0cf5ca27c99987d18177b8bf8d17bbf855fdd4a0dd52898b2707a2b7aa04"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.x86_64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c20f4bbb4f972e2f132d3e48c50b756ae34b2775"
gpu = "cuda"
gpu_version = "13.0"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "be1ef481ac2321cc39ff7e3cf011a8968ff6505793762c52ddd26641f1790a9d"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.aarch64-linux-gnu-cxx11-gpu_version+13.0-gpu+cuda-mode+opt.tar.xz"
[[Reactant]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "917f2d1d23fb1c7c3975d28fc55681c4a6ee982d"
gpu = "rocm"
gpu_version = "7.1"
lazy = true
libc = "glibc"
mode = "opt"
os = "linux"

    [[Reactant.download]]
    sha256 = "a20cbc723fe6b807c9d8b655846345c900359e04642063de6bf0f14553d7354b"
    url = "https://github.com/EnzymeAD/Reactant_jll.jl/releases/download/Reactant-v0.0.300+0/Reactant.v0.0.300.x86_64-linux-gnu-cxx11-gpu_version+7.1-gpu+rocm-mode+opt.tar.xz"
