[[LAME]]
arch = "aarch64"
git-tree-sha1 = "ebbb9485b8a2f32f9ab907b08b38b039acaae6cf"
os = "macos"

    [[LAME.download]]
    sha256 = "4e5a9861d11f73e3ba59cc68cf4d8fed4a524575e4169320cfbadfd2e705cd27"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.aarch64-apple-darwin.tar.gz"
[[LAME]]
arch = "aarch64"
git-tree-sha1 = "6ab3d0ec88a054941a0c8d9981d1a485b8983dfe"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "2c9f5135bbbd403877b4c1f76dcd0dcad01e8ae4ddf893ea0438f22a047c83d5"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.aarch64-linux-gnu.tar.gz"
[[LAME]]
arch = "aarch64"
git-tree-sha1 = "774ee7f7f0fad88df6482f8cd0305c8e673ed897"
libc = "musl"
os = "linux"

    [[LAME.download]]
    sha256 = "6d61431be7df4be5c0d0fb5381cb86b883644d8863b89abcafd94be964fb8c9e"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.aarch64-linux-musl.tar.gz"
[[LAME]]
arch = "aarch64"
git-tree-sha1 = "3949052e7f04e6915a3857a991a61c92360dfb5e"
os = "freebsd"

    [[LAME.download]]
    sha256 = "16d75016fba6a38d43e199505ef07e0e27c4d3065081eb1d1a2d3e6991f05667"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.aarch64-unknown-freebsd.tar.gz"
[[LAME]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3ccdaba7f2fe3dd5bbe149059001034dbb875855"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "de5563bcbc9fb6042675f202a691fc81780c259cc891437ba4e1c76060a1c9a6"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.armv6l-linux-gnueabihf.tar.gz"
[[LAME]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "33bf7eb901b17490da1d361feaec58a17b89c8c5"
libc = "musl"
os = "linux"

    [[LAME.download]]
    sha256 = "e5a2f2a655514c49b18c368ec627297a2d93c9f8c9beb25fec8d41f8ec5c582a"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.armv6l-linux-musleabihf.tar.gz"
[[LAME]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f0587142a6f25a3874ee45630fee93c78a7b8d77"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "8caeed48bf2c3e91c0a33d1f601f81eba5cec04e25c7ff192e8a1233c9e30242"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.armv7l-linux-gnueabihf.tar.gz"
[[LAME]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ca0400d86f4aff3195e6994795ca36b456071e66"
libc = "musl"
os = "linux"

    [[LAME.download]]
    sha256 = "d0986de2baaca7c8fd5da5369660901ba7581636cebd8fd7cec9eaa6f2a86eaa"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.armv7l-linux-musleabihf.tar.gz"
[[LAME]]
arch = "i686"
git-tree-sha1 = "c2aaf38c4fcb2c211f2de818b1e159884997921f"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "e0789a6387c495d971e0d0152b242606b7af24814a3af5847be0e53fd08b0db2"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.i686-linux-gnu.tar.gz"
[[LAME]]
arch = "i686"
git-tree-sha1 = "ed378c388bf96b7d59372b5f1ca1fdcade9a2792"
libc = "musl"
os = "linux"

    [[LAME.download]]
    sha256 = "5bd44368e9c4d2cc1e1b2b9b89d16600355862859fdca243841fcaa5a93e5d1a"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.i686-linux-musl.tar.gz"
[[LAME]]
arch = "i686"
git-tree-sha1 = "b672ab10dbc533621ebd86b13498b626ed2870f7"
os = "windows"

    [[LAME.download]]
    sha256 = "919645359e5141e7e0c6d3dd1e95fe4c03f6e1d808ff7e784c56cacb4a802982"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.i686-w64-mingw32.tar.gz"
[[LAME]]
arch = "powerpc64le"
git-tree-sha1 = "8ee886ca74a19f3d4dd928f49ffc4a28ba03a6d5"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "35abdd817c14f8181571994aa904d2f6ff849ee623158a129a40c28b86f62cec"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.powerpc64le-linux-gnu.tar.gz"
[[LAME]]
arch = "riscv64"
git-tree-sha1 = "02cf215ea11021b35a00bc8c716541d92a45883b"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "bb5357d9e067ef78b1ba6eb0b535b2ae6f22f52593023312fe9992e4538dea9d"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.riscv64-linux-gnu.tar.gz"
[[LAME]]
arch = "x86_64"
git-tree-sha1 = "8c132fe5059ed4f3dac6a13f9f185c40c95d2070"
os = "macos"

    [[LAME.download]]
    sha256 = "9e805904143a35ee8254d0476aeb83ca8ecfc3b921c2aa4288734a6ed870ed47"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.x86_64-apple-darwin.tar.gz"
[[LAME]]
arch = "x86_64"
git-tree-sha1 = "c8a20a2030f10b70947d8d2a6bff7f8b5f343fe9"
libc = "glibc"
os = "linux"

    [[LAME.download]]
    sha256 = "d3d39cc049655810b16fdfd49a946d01261396e86ad0d6c2b79b7360166efffd"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.x86_64-linux-gnu.tar.gz"
[[LAME]]
arch = "x86_64"
git-tree-sha1 = "20dd12b251be119395788d9a8a6e29dd3355c147"
libc = "musl"
os = "linux"

    [[LAME.download]]
    sha256 = "6b5046ca511784843c363f5f4756563a391fa231009e49b694e80b187bd4133b"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.x86_64-linux-musl.tar.gz"
[[LAME]]
arch = "x86_64"
git-tree-sha1 = "495577983c7c90f8eca00797c36f42df0ca65479"
os = "freebsd"

    [[LAME.download]]
    sha256 = "0cedb6af813c587bdf1d4cd6ee82eb0d28c2c867a49587ec744c9b564c347e59"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.x86_64-unknown-freebsd.tar.gz"
[[LAME]]
arch = "x86_64"
git-tree-sha1 = "81ad3b6f8af8fa057c1a9640ca91454b669b342b"
os = "windows"

    [[LAME.download]]
    sha256 = "e650deb6978086bde7ab5852d9190b4cec83aa9196c129a2a3a34370fde10b17"
    url = "https://github.com/JuliaBinaryWrappers/LAME_jll.jl/releases/download/LAME-v3.100.3+0/LAME.v3.100.3.x86_64-w64-mingw32.tar.gz"
