[[Xorg_libICE]]
arch = "aarch64"
git-tree-sha1 = "617d04e1cd3000d521acecd36498d1c97fda4154"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "ca5ff17a8e890408010c3c7fc0ebac41882451586c502789a2347641f90028b5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.aarch64-linux-gnu.tar.gz"
[[Xorg_libICE]]
arch = "aarch64"
git-tree-sha1 = "3df0ecf231b3a8978b74dcc0f6ee6f1c4bacc9e2"
libc = "musl"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "2acb3e7ca002627cead732a1b72a6f19270fd2f62fd47b233f87f2ad783470f8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.aarch64-linux-musl.tar.gz"
[[Xorg_libICE]]
arch = "aarch64"
git-tree-sha1 = "fe6bc37cbd2048e4fc6339590578b6423ced7431"
os = "freebsd"

    [[Xorg_libICE.download]]
    sha256 = "6dfc4db47876b14cc7f20e9e5438a642154a17950b54461b37cc807c95b17179"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libICE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "94255ffaef8538cf18e2d3d8488b0304f6587955"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "87bf2d666f8d305f6fc7a32fd6bb7ea375f6c6babf4213d0f0b2dc75f045cd33"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libICE]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "990007d437b9edce17fb1e89d3948360789a7e36"
libc = "musl"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "fcac7276b8cc9a9aecdd5304895b147c6346cb03e0e2c4e33e29c1a9c6b1500c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libICE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03739663cb627e7cdfd13966bc96c4b56016fb83"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "255be179284d22420f692f3f1dc064390f25cbd0ffa9c491bf9fbb4455a70710"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libICE]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3b338934829f63f726817e3f6de172de9cdfc765"
libc = "musl"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "34d91a5460c388e126d615f8e8f209014ce1514243aa85138611b07186cbcaf9"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libICE]]
arch = "i686"
git-tree-sha1 = "a0dcdc450c84af02432591cebc4020f7cf792121"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "3bbb1bdbbe541bd81f0a522c8a6c7792ad86522b944d734da6fde28acd93f2ed"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.i686-linux-gnu.tar.gz"
[[Xorg_libICE]]
arch = "i686"
git-tree-sha1 = "9708985d7b8b3c025a2e1b7df613c4c52d950421"
libc = "musl"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "963e58966288c7ae77d722eea65b5a26caa48944e86f27739382f42cf981ac0d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.i686-linux-musl.tar.gz"
[[Xorg_libICE]]
arch = "powerpc64le"
git-tree-sha1 = "0e2cc7a7176a68df192efd2cbb5339a3a63388c9"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "62a163124e7f3144ae0d96e4b634883982750a3d96c42a5803c90788240b3a7d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libICE]]
arch = "riscv64"
git-tree-sha1 = "4ae5593a7011f6088d9d1e9f456f67a1be68d819"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "1e766d17bc8191b704a247bc1fb3d7cdc7ed4550907f39849e643e7ab19c5719"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.riscv64-linux-gnu.tar.gz"
[[Xorg_libICE]]
arch = "x86_64"
git-tree-sha1 = "443e05ab3771707793cdec96039306b08738a626"
libc = "glibc"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "f66b19fbf2c970583066043151b5603ee5f5fe576241114585bbe08c0c1dd06d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.x86_64-linux-gnu.tar.gz"
[[Xorg_libICE]]
arch = "x86_64"
git-tree-sha1 = "d9b3cd6fd1fb11b0d94b8a82256099c8130f4d35"
libc = "musl"
os = "linux"

    [[Xorg_libICE.download]]
    sha256 = "bb852b9ef16e5ba649a25d12da5e7ab502325a20c4d2bbece1e98d35b063b50a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.x86_64-linux-musl.tar.gz"
[[Xorg_libICE]]
arch = "x86_64"
git-tree-sha1 = "4add6f92e07c12173c87cdce573cd735c2ce3818"
os = "freebsd"

    [[Xorg_libICE.download]]
    sha256 = "4a6927329117f0d564bd69b0f22ca29b25bf4afceac34f17db8c6b2ec577c6b8"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libICE_jll.jl/releases/download/Xorg_libICE-v1.1.2+0/Xorg_libICE.v1.1.2.x86_64-unknown-freebsd.tar.gz"
