[[Xorg_xcb_util_wm]]
arch = "aarch64"
git-tree-sha1 = "2f0682002765f55c72c0f942760e43d9ba6ecdc7"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "8077ad09ba5cf87282f2d5936270645e57d77cb3de35bca48b50b5117e8dd37b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "aarch64"
git-tree-sha1 = "e7fdbd50fe9cca312c07109eb202240906b962be"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "f0284b6b08cf1d8118ad07645cb2cd03a9bbb7160ac9b718791e3bec943af8a5"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "aarch64"
git-tree-sha1 = "9c2ff4ad39f83c367f3f4cabc911dbc8af83387e"
os = "freebsd"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "b8eda75f7276eb871470537113afff111f2606086343817691221fef202d367c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.aarch64-unknown-freebsd.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cdc988039e113302b8c1ece6acb1d0bc153b5feb"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "bab591783bb5ce52f42880c6fcdd81966348ee2e78469994ed491097616ff89f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9c1397bc631903b620135b090be6b83d25cc5965"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "b22d3e63090ab9ff591b21deaedafe54afd513304805500731cdb3ba53466ff0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.armv6l-linux-musleabihf.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f840380f3634f32712f7ac12015a48794cdbd807"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "55dd093d889a11d98b53de0942bf65fbf9c262185ceb138f58a44f2c9d1d2cee"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "db8034b607ae53fbc16d427022bc76ae87aac5be"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "9933721f88af1d25468fb16d16518fcf7b0413c7f467d8ce5a4e71e32d6c255e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "i686"
git-tree-sha1 = "0fdffd41b19e73173883b10c4bc49129094e49a9"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "191ddcc6d2d53f3f3550fbfd1ba6e5a72c4aa9e676c231f3a0c76dc7944411b4"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.i686-linux-gnu.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "i686"
git-tree-sha1 = "9ab730ec5aff7215ab24531c408bb5942d9fb0ba"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "0106de9bd727ab6deb9efe0063a872c678bab343d019f58584d3f7defa054fc1"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.i686-linux-musl.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "powerpc64le"
git-tree-sha1 = "3ee0602f40085271b8b14b2c66a0f7e8b30a79c2"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "a69612b36a8a6d7539193bdd3afe3d1b4f427491b8ca5c3c65a2930143acef10"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "riscv64"
git-tree-sha1 = "3e21e23e741c27d920ca9d4aaee3e260752e4978"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "f192828864a1ff2d488eaa000091dcd00943e7615da2ee18fb049670771f7303"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.riscv64-linux-gnu.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "x86_64"
git-tree-sha1 = "80000680ee2829d8f281d77c90e2d1d02f031865"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "af82e3a4ff4c592b8c3b1aa1def0d70464d2be8d74390494fe034a9bc3aaf736"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "x86_64"
git-tree-sha1 = "79010f98ff5a14650cede0ca3aa7cb16aa651cd3"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "ddfd900b742b64b3e6babb2210f35d2429aa157e4081ad6961af0115f967b550"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_util_wm]]
arch = "x86_64"
git-tree-sha1 = "56e0820f2e06074a7c7b2a5372fd55d8175f081d"
os = "freebsd"

    [[Xorg_xcb_util_wm.download]]
    sha256 = "00ade1fdfbfd9a65adbda4e383dfec80913be501f32e85631a94ec0195536053"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_wm_jll.jl/releases/download/Xorg_xcb_util_wm-v0.4.2+0/Xorg_xcb_util_wm.v0.4.2.x86_64-unknown-freebsd.tar.gz"
