[[Imath]]
arch = "aarch64"
git-tree-sha1 = "2cbecda271d0e218ffc6a31810152d29fc8fe9ff"
os = "macos"

    [[Imath.download]]
    sha256 = "6a4e7fe53e48ae1a5db28ef0cebf30fb7482f8a757a88d3f57545fba08bedb55"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.aarch64-apple-darwin.tar.gz"
[[Imath]]
arch = "aarch64"
git-tree-sha1 = "bd7e4534eb6925098ec781e910843bca4d5a4f03"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "4d17b4c9ffdf89710cec8913120fbae603047a9f459f5f2af4eec8be410a4906"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.aarch64-linux-gnu.tar.gz"
[[Imath]]
arch = "aarch64"
git-tree-sha1 = "e52018b674acf70b89030758a39078c7da8103c2"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "6e93848f523377ec4cc78b2f464d384446053b73e9431eee7d6a6d8cb6712a32"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.aarch64-linux-musl.tar.gz"
[[Imath]]
arch = "aarch64"
git-tree-sha1 = "8f287f20bf0af0e25f41272548a2e34097875ac0"
os = "freebsd"

    [[Imath.download]]
    sha256 = "ef58cbd84351cd793a417db5ba78ec1d9d476f2846988f349f8754e05dce5cd5"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.aarch64-unknown-freebsd.tar.gz"
[[Imath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aeca49b043362541f11a10095caec3bd86f7bed1"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "62b6a014e5089819c6043301ab320848aab27c42b32f9df96a11fe77373f959d"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.armv6l-linux-gnueabihf.tar.gz"
[[Imath]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c350b9690341d2250bb39b8422f6d8511c81cfe1"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "1b8e3e2c7ce743591864802f18165f04dd018c244ac9293e4e8fe2818f0d5d8c"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.armv6l-linux-musleabihf.tar.gz"
[[Imath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "873c75f65d498dc566b8bb4a97610b530807d4cf"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "25aa6e196f7647fd02a1d15704cd3a330770a8b658d4e2918b69de64833167ca"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.armv7l-linux-gnueabihf.tar.gz"
[[Imath]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c76c0fec0f2c57e8cab40590ce0db78d071c0c31"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "e1cddb11d04025460c4bbeff38e6188e5f2d66e6a7189b0541a8b3351a476b43"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.armv7l-linux-musleabihf.tar.gz"
[[Imath]]
arch = "i686"
git-tree-sha1 = "dff9e880abf9fec87cc28b81602f46c9c7b4803a"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "cf7df7f643d106172764d1b19e8d1a9da6c09aed21a8630a907f4cd3dcbee8cf"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.i686-linux-gnu.tar.gz"
[[Imath]]
arch = "i686"
git-tree-sha1 = "61e60053da56c7da0cf72e8dadccbc74d115de99"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "2ffa870856c33cdac8cce3ec71d06a8fad35eaccd9a1f38d408a8752f627636b"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.i686-linux-musl.tar.gz"
[[Imath]]
arch = "i686"
git-tree-sha1 = "a2b3e4bbae1aa84b3c08f3bcd2fa7a4dab269dc1"
os = "windows"

    [[Imath.download]]
    sha256 = "97eb3a705f3077a89d4ee04f4c69b5bd8f33fc287f34d45160ac72d3d83dc46f"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.i686-w64-mingw32.tar.gz"
[[Imath]]
arch = "powerpc64le"
git-tree-sha1 = "165d6dbcf167301e59980b36bb696a8533823dd8"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "a7ff073fbb5740785dc04218abd62ff7eb901c4526c072c9c2df15d2ba1194a3"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.powerpc64le-linux-gnu.tar.gz"
[[Imath]]
arch = "riscv64"
git-tree-sha1 = "963bd7de86a1ca93ec6e07e396c7294ee96d45bc"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "500d2f41950f589adb7f3325e96fea35ebc62fd7bfb9babb311ea8875603fe86"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.riscv64-linux-gnu.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "d90bf78948ae501af676791ef5adfb7ba2d0f86c"
os = "macos"

    [[Imath.download]]
    sha256 = "b8b3eab35ddd6a04dc7a40054880f4c84530d5fcc632072683050419ff2ca9cd"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.x86_64-apple-darwin.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "7cb9c692890e426e45dd8bf382aa07cff4500178"
libc = "glibc"
os = "linux"

    [[Imath.download]]
    sha256 = "222cc4cf96512e490818de8fb0105e86e1302c59a684bd4b68b1851252985b9c"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.x86_64-linux-gnu.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "c351e1243ea0edaf8f709433660fb9d8f2c6885a"
libc = "musl"
os = "linux"

    [[Imath.download]]
    sha256 = "9f81bf003ead5c9bf22c0d68d8b58c7f070f0145e2c79bda5ba40c4095a3abc1"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.x86_64-linux-musl.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "f1bb9bea1b9de4e234f79510f61f737645d0c3f2"
os = "freebsd"

    [[Imath.download]]
    sha256 = "7c2f50d4978644e6dcfc8e0d85ef52255e44603581fa771082d5e42f854faeba"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.x86_64-unknown-freebsd.tar.gz"
[[Imath]]
arch = "x86_64"
git-tree-sha1 = "82355716bd7992103b9ee2b05222b88294698919"
os = "windows"

    [[Imath.download]]
    sha256 = "054241d7c1f2b1eed8429f69b3554febeb70a80b0c12c31f9d0c557f911d4d7f"
    url = "https://github.com/JuliaBinaryWrappers/Imath_jll.jl/releases/download/Imath-v3.2.2+0/Imath.v3.2.2.x86_64-w64-mingw32.tar.gz"
