[[mtdev]]
arch = "aarch64"
git-tree-sha1 = "3bd8235883e9a2b1c4475a84cf2f3cf747299f0a"
libc = "glibc"
os = "linux"

    [[mtdev.download]]
    sha256 = "0e54cd822cdf41c7527ee97a23e45c59e13a833cf2eab3c7af663aa0a8109788"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.aarch64-linux-gnu.tar.gz"
[[mtdev]]
arch = "aarch64"
git-tree-sha1 = "a65a4a98f5d62bab9767df49ceba24155bb6b4ba"
libc = "musl"
os = "linux"

    [[mtdev.download]]
    sha256 = "776fb76a1fdbc9115caa7146b73e98503a6bed7f4915e6c40df9fc1676d26543"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.aarch64-linux-musl.tar.gz"
[[mtdev]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fe5d9aad97b275ce98987c4896581690415294c9"
libc = "glibc"
os = "linux"

    [[mtdev.download]]
    sha256 = "77f06467656d12287d646020e1e60d5ad626f4b3ae4ff23e08d55f9236eba1af"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.armv6l-linux-gnueabihf.tar.gz"
[[mtdev]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5a310fcb96bf8a386620a78b4d380b7489dceb2b"
libc = "musl"
os = "linux"

    [[mtdev.download]]
    sha256 = "c8b9367ff423b90005b09a29e859aab76810d036fd37a03c590345256b478ea5"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.armv6l-linux-musleabihf.tar.gz"
[[mtdev]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a83090aacd5dd8cef62d873551ff3be226b0eebc"
libc = "glibc"
os = "linux"

    [[mtdev.download]]
    sha256 = "e6c2510b94cb4e00562ea050779fe69f166958e825b0ec3880cecc62ba8a5ca8"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.armv7l-linux-gnueabihf.tar.gz"
[[mtdev]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e1997df14d1e2d51754780749d37cc1d4ebc1ad7"
libc = "musl"
os = "linux"

    [[mtdev.download]]
    sha256 = "6e4b19a70c6b1b2eba9a7e475a4238b4f9de96c1fc102564e4de09b76a5425a4"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.armv7l-linux-musleabihf.tar.gz"
[[mtdev]]
arch = "i686"
git-tree-sha1 = "70950e18e8b4c19432d12f5575f9be492be4a26d"
libc = "glibc"
os = "linux"

    [[mtdev.download]]
    sha256 = "331dcb45767821182b047095649ec4dce32ef09b62b54e5a9579844b78f5f5cd"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.i686-linux-gnu.tar.gz"
[[mtdev]]
arch = "i686"
git-tree-sha1 = "ea30ec5d60c3d7ab683c553e97af2704388c723b"
libc = "musl"
os = "linux"

    [[mtdev.download]]
    sha256 = "b7f8c00acac009031a672e6987e8b826ebce9e0b01de8a885f677b6baf2e653f"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.i686-linux-musl.tar.gz"
[[mtdev]]
arch = "powerpc64le"
git-tree-sha1 = "d23b68e392857b2870c3fa79d9e31ea4d89eef00"
libc = "glibc"
os = "linux"

    [[mtdev.download]]
    sha256 = "ef23f0a656c937a73126185141b304108c08827c747ec5588ea04488966ca40b"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.powerpc64le-linux-gnu.tar.gz"
[[mtdev]]
arch = "riscv64"
git-tree-sha1 = "89a6d3d31b54632104520ff6709c428c4d9c395d"
libc = "glibc"
os = "linux"

    [[mtdev.download]]
    sha256 = "09bc2e02abdde74ca786800f3d363c50c1ab174e6755d0c48530634a506a584a"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.riscv64-linux-gnu.tar.gz"
[[mtdev]]
arch = "x86_64"
git-tree-sha1 = "9f964aa3f8c584bef017178cda25ba9d29e37c3b"
libc = "glibc"
os = "linux"

    [[mtdev.download]]
    sha256 = "335ae34be78760d13cbd9fba7dfc5d9bf2e184aefd8faa26d3028df4c2283479"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.x86_64-linux-gnu.tar.gz"
[[mtdev]]
arch = "x86_64"
git-tree-sha1 = "538ff955192a1c2ef581e0088535f3b9aa66ba5d"
libc = "musl"
os = "linux"

    [[mtdev.download]]
    sha256 = "aea38540e455254f922be48413d2c7a8e1373b931c3ee1b0506c5210b57dfc52"
    url = "https://github.com/JuliaBinaryWrappers/mtdev_jll.jl/releases/download/mtdev-v1.1.7+0/mtdev.v1.1.7.x86_64-linux-musl.tar.gz"
