[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "710683e8a2982e750d263294a2603a7455eaf783"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "21c0d2b4f600204880b5fada08defdb212cc8c2ad36206f52e49b08fb172902b"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.aarch64-linux-gnu.tar.gz"
[[Libmount]]
arch = "aarch64"
git-tree-sha1 = "7f9e8221bd06920212ff48863de98f72caa6d869"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "d10c75c628e7c929ab0f8a493aa117983a10aeb0638abd82e4b659abd3a84643"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.aarch64-linux-musl.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "423d340efd011b78f5e809cafab06bfc77a65ba6"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "64e362f3cbe5453ceb3afdec0a6ece8db179dbe5a4c56b7ca790cb5d40a07c36"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.armv6l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "234a8a2550d39214276e37725b6f89abdae5dc03"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "97c571df9c1afff1c8deb6b483df1e4a2114e6bab948c14a4506f9d2bfebf7d2"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.armv6l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b96a386586b8f1c81c888decac8855482b1eba5"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "d049c1b67d9a328c39c6c749bdacb086e310d6e67aaa7a445c909a95ee677124"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.armv7l-linux-gnueabihf.tar.gz"
[[Libmount]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0dad87bbb9185d6f82e7d71c76d5898354574dd9"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "c0d3668a7bd6efcfea9fae69bb5f85ee398bb25fe4258a53ee2135f5b1609167"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.armv7l-linux-musleabihf.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "6b361feb6eee83921d6c7a9692551511e9e06a10"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "7b2a872bee1d5cbaf3986145f863941581131c910b9e44d3175d511046fa01de"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.i686-linux-gnu.tar.gz"
[[Libmount]]
arch = "i686"
git-tree-sha1 = "85910c64faf134f7fb3ecf37f139a7f3634633be"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "f76cf25f64597ccb3fa713bc0b6c358ca33e0256e9f0ad396512af3e1b9b1dd0"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.i686-linux-musl.tar.gz"
[[Libmount]]
arch = "powerpc64le"
git-tree-sha1 = "702f55adbe0c1b5c96f348959e01df8d90fb6a35"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "91bbb37503ba2ec11f9761f90c57da28a259aee63f9fef5b9896bea3b52e045c"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.powerpc64le-linux-gnu.tar.gz"
[[Libmount]]
arch = "riscv64"
git-tree-sha1 = "e87710f7101bd59bb931d296ca545c0c03b43025"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "d69c502e02c6a6df8ef4c22fc53efe571fae188af74e217a18f92c0d1eadfa61"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.riscv64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "8b3afca91045179066b09b7a57f208894c50f3fa"
libc = "glibc"
os = "linux"

    [[Libmount.download]]
    sha256 = "23d589ceef0d140bb2d5ada67a69484ae1b64f3b18e794848f1e0dc790581d05"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.x86_64-linux-gnu.tar.gz"
[[Libmount]]
arch = "x86_64"
git-tree-sha1 = "61f784e6b0d721f47297cf3082ca138f57ac120d"
libc = "musl"
os = "linux"

    [[Libmount.download]]
    sha256 = "2133e5660a384fadb27bdc174f4ae0d3589fdb0e71df8c21cb598874db9b47a3"
    url = "https://github.com/JuliaBinaryWrappers/Libmount_jll.jl/releases/download/Libmount-v2.41.2+0/Libmount.v2.41.2.x86_64-linux-musl.tar.gz"
