[[Xorg_xcb_util_image]]
arch = "aarch64"
git-tree-sha1 = "0b0bfbd3c3ea23fce82c3ae2777c6add3e244175"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "7bb46872d6a6e5f6ca8a3a952fd221c93f3d10f92a7b064545a491953e809a83"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.aarch64-linux-gnu.tar.gz"
[[Xorg_xcb_util_image]]
arch = "aarch64"
git-tree-sha1 = "8598770f559931e0d3a7d04bf7ce1d34aeb1f513"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "ff18951f51a2523969b1de51b12da19879e97cb39aa9f6835f8305b411ab4530"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.aarch64-linux-musl.tar.gz"
[[Xorg_xcb_util_image]]
arch = "aarch64"
git-tree-sha1 = "45fa8acc1f5f7f11d6e4a1babfdb4c1fcd3d2f51"
os = "freebsd"

    [[Xorg_xcb_util_image.download]]
    sha256 = "90320f950d3f02abf8744e816df1c02c8bdf11aa7d14419b4c6f262b4bb91176"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.aarch64-unknown-freebsd.tar.gz"
[[Xorg_xcb_util_image]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "449f5b12d27496fa08e3392b2089501d4d590388"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "5a6b7caeb2c5f595f250532f311431f2eadd87272f739c43ac49750d6efddcd6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_image]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f133456257fd0fbe2aeaf8c354b1697745f0c5ef"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "e34d1d6b7f3f3bcd6a481c7340029d894a51a1138041917ef084240dfc282fbe"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.armv6l-linux-musleabihf.tar.gz"
[[Xorg_xcb_util_image]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "27da4501ee42533ac246440afb6936269b3ab730"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "182dcd110a2c8a1118a8fb3d8aa64e17e039cfa242f5b5e0f3c2936ae732067d"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_xcb_util_image]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b4a6762c19eb5f20191f6b8f3e2832af99ee7f5c"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "d3a7882384ebf345adedc1dc93c28fb3f58934b479049d3021d772ed61145a3c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.armv7l-linux-musleabihf.tar.gz"
[[Xorg_xcb_util_image]]
arch = "i686"
git-tree-sha1 = "8c0e53b07ca77ebcfc2eca049c66e84f21fd1016"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "adfef118492aac0e147367b1dd22d00a170034df2e7233a8d846fa71e43c13c6"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.i686-linux-gnu.tar.gz"
[[Xorg_xcb_util_image]]
arch = "i686"
git-tree-sha1 = "7cfa2654145a9783dfe6ae769a72de04c4116acb"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "7fc16dda94cfe8d5fa26fe0b622e48f93d7d57bf73f11a3cba3600ecf2b1f18c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.i686-linux-musl.tar.gz"
[[Xorg_xcb_util_image]]
arch = "powerpc64le"
git-tree-sha1 = "abf7db335cc01e893bfec9a80f49f3d59fd0e44b"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "4d64702fc192c65bc8bb44ef61a463d8bed42c7adf90ea1e8361251a4f9e312a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.powerpc64le-linux-gnu.tar.gz"
[[Xorg_xcb_util_image]]
arch = "riscv64"
git-tree-sha1 = "27a29b74f118c6d8d282f4f79e7a804906d36c5b"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "89a432ab4cf39e4365fb949a9a642b25cd7517b195f1e1fc2dd369b50bbcbd6b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.riscv64-linux-gnu.tar.gz"
[[Xorg_xcb_util_image]]
arch = "x86_64"
git-tree-sha1 = "644dabe7eac7b955e9d4b63449550d6ab77800e6"
libc = "glibc"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "0747425017716535d7c436f827ec56fed59b40b5d2f1116149cc60b1e9a08214"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.x86_64-linux-gnu.tar.gz"
[[Xorg_xcb_util_image]]
arch = "x86_64"
git-tree-sha1 = "06ab1686cce904940f4f7333f8e7a292f4c28772"
libc = "musl"
os = "linux"

    [[Xorg_xcb_util_image.download]]
    sha256 = "4463155acf883720c09afc83bb5964687da596614f26ee4aa1525f0bd729667e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.x86_64-linux-musl.tar.gz"
[[Xorg_xcb_util_image]]
arch = "x86_64"
git-tree-sha1 = "74f749de57ce56af2be2b68abc0db2acec200c7a"
os = "freebsd"

    [[Xorg_xcb_util_image.download]]
    sha256 = "e0bc7c0bf9b76b036a3e0921ff748b8f8b3a34313e099939298c34b931ccff92"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_xcb_util_image_jll.jl/releases/download/Xorg_xcb_util_image-v0.4.1+0/Xorg_xcb_util_image.v0.4.1.x86_64-unknown-freebsd.tar.gz"
